// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Belatrix.Ebay.API.Screens.Home.HomeClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class Home
    {
        
        #region Properties
        public UIHomePage UIHomePage
        {
            get
            {
                if ((this.mUIHomePage == null))
                {
                    this.mUIHomePage = new UIHomePage();
                }
                return this.mUIHomePage;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePage mUIHomePage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePage : BrowserWindow
    {
        
        public UIHomePage()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public Body Body
        {
            get
            {
                if ((this.mBody == null))
                {
                    this.mBody = new Body(this);
                }
                return this.mBody;
            }
        }
        #endregion
        
        #region Fields
        private Body mBody;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Body : HtmlDocument
    {
        
        public Body(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.ebay.com/";
            this.WindowTitles.Add("Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink AdvancedSearch
        {
            get
            {
                if ((this.mAdvancedSearch == null))
                {
                    this.mAdvancedSearch = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mAdvancedSearch.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "gh-as-a";
                    this.mAdvancedSearch.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mAdvancedSearch.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mAdvancedSearch.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Búsqueda avanzada";
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/sch/ebayadvsearch";
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Búsqueda avanzada";
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://www.ebay.com/sch/ebayadvsearch";
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Búsqueda avanzada\" id=\"gh-as-a\" h";
                    this.mAdvancedSearch.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "49";
                    this.mAdvancedSearch.WindowTitles.Add("Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay");
                    #endregion
                }
                return this.mAdvancedSearch;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mAdvancedSearch;
        #endregion
    }
}
