// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Belatrix.Ebay.API.Screens.SearchAdvanced.AdvancedSearchClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class AdvancedSearch
    {
        
        #region Properties
        public UISearchAdvancedPage UISearchAdvancedPage
        {
            get
            {
                if ((this.mUISearchAdvancedPage == null))
                {
                    this.mUISearchAdvancedPage = new UISearchAdvancedPage();
                }
                return this.mUISearchAdvancedPage;
            }
        }
        #endregion
        
        #region Fields
        private UISearchAdvancedPage mUISearchAdvancedPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISearchAdvancedPage : BrowserWindow
    {
        
        public UISearchAdvancedPage()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Búsqueda en eBay: Búsqueda avanzada";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public Body Body
        {
            get
            {
                if ((this.mBody == null))
                {
                    this.mBody = new Body(this);
                }
                return this.mBody;
            }
        }
        #endregion
        
        #region Fields
        private Body mBody;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Body : HtmlDocument
    {
        
        public Body(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Búsqueda en eBay: Búsqueda avanzada";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/sch/ebayadvsearch";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.ebay.com/sch/ebayadvsearch";
            this.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
            #endregion
        }
        
        #region Properties
        public HtmlEdit KeyWordArticle
        {
            get
            {
                if ((this.mKeyWordArticle == null))
                {
                    this.mKeyWordArticle = new HtmlEdit(this);
                    #region Search Criteria
                    this.mKeyWordArticle.SearchProperties[HtmlEdit.PropertyNames.Id] = "_nkw";
                    this.mKeyWordArticle.SearchProperties[HtmlEdit.PropertyNames.Name] = "_nkw";
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"_nkw\" id=\"_nkw\" aria-labelledby=\"k";
                    this.mKeyWordArticle.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mKeyWordArticle.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
                    #endregion
                }
                return this.mKeyWordArticle;
            }
        }
        
        public HtmlComboBox Category
        {
            get
            {
                if ((this.mCategory == null))
                {
                    this.mCategory = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mCategory.SearchProperties[HtmlComboBox.PropertyNames.Id] = "e1-1";
                    this.mCategory.SearchProperties[HtmlComboBox.PropertyNames.Name] = "_sacat";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = @" En esta categoría:
Todas las categorías Antiguos Arte Artesanías Artículos deportivos Bebés Belleza y salud Bienes raíces Cámaras y fotografía Celulares y accesorios Cerámica y vidrio Computadoras, tablets y redes Equipo y maquinaria industrial Estampillas Hogar y jardín Instrumentos y equipos musicales Joyería y relojes Juguetes y pasatiempos Libros Memorabilia de deporte, tarjetas, fans Memorabilia de entretenimiento Monedas y billetes Muñecas y osos Música Objetos de colección Películas y DVD Productos para mascotas Ropa, calzado y accesorios Servicios especiales Tarjetas de regalo y cupones Tecnología Viaje Videojuegos y consolas Todo lo demás ";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "34";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.Class] = "block";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"_sacat\" class=\"block\" id=\"e1-1\"";
                    this.mCategory.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "2";
                    this.mCategory.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
                    #endregion
                }
                return this.mCategory;
            }
        }
        
        public ContainerSearch ContainerSearch
        {
            get
            {
                if ((this.mContainerSearch == null))
                {
                    this.mContainerSearch = new ContainerSearch(this);
                }
                return this.mContainerSearch;
            }
        }
        
        public HtmlList CategoryList
        {
            get
            {
                if ((this.mCategoryList == null))
                {
                    this.mCategoryList = new HtmlList(this);
                    #region Search Criteria
                    this.mCategoryList.SearchProperties[HtmlList.PropertyNames.Name] = "_sacat";
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.Size] = "30";
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.Title] = null;
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.ItemCount] = "34";
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.Class] = null;
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.ControlDefinition] = "style=\"border: 2px solid rgb(33, 33, 33)";
                    this.mCategoryList.FilterProperties[HtmlList.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mCategoryList;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mKeyWordArticle;
        
        private HtmlComboBox mCategory;
        
        private ContainerSearch mContainerSearch;
        
        private HtmlList mCategoryList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class ContainerSearch : HtmlCustom
    {
        
        public ContainerSearch(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "adv_search_from";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "adv_search_from";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "name=\"adv_search_from\" id=\"adv_search_fr";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
            #endregion
        }
        
        #region Properties
        public HtmlButton ButtonSearch
        {
            get
            {
                if ((this.mButtonSearch == null))
                {
                    this.mButtonSearch = new HtmlButton(this);
                    #region Search Criteria
                    this.mButtonSearch.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mButtonSearch.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mButtonSearch.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Buscar";
                    this.mButtonSearch.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mButtonSearch.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mButtonSearch.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-prim";
                    this.mButtonSearch.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-prim\" onclick=\"return fal";
                    this.mButtonSearch.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mButtonSearch.WindowTitles.Add("Búsqueda en eBay: Búsqueda avanzada");
                    #endregion
                }
                return this.mButtonSearch;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mButtonSearch;
        #endregion
    }
}
